### PR TITLE
#152796966 Create template pages that enable a user to add events

### PR DESCRIPTION
**Pull request by chinemelu**
#### What does this PR do?
Create template page that enables a user to add events

#### What are the relevant pivotal tracker stories?
#152796966   

#### Screenshots 
screenshot 3

### CODE REVIEW

**Comment by chinemelu** [comment]
@andela-uibrahim, please review this pull request

**Comment by freemile2ru** [comment]
@chinemelu please check for appropriate PR naming conventions and comment

**Review by freemile2ru — COMMENTED** [review]
too many file changes. please put libraries in a gitignore file. no need to push them

**Comment by freemile2ru** [comment]
also fix merge conflicts

**Pull request merged**
